### PR TITLE
Fix results hpc

### PR DESCRIPTION
**Pull request by b10n1k**

### CODE REVIEW

**Comment by b10n1k** [comment]
https://aquarius.suse.cz/tests/18332/file/slurm_master-TEST-hpc-test.xml

**Review by schlad — CHANGES_REQUESTED** [review]
I'm a bit confused why do you try to do this.

It might be good idea to have such tests and as a matter of fact I did experiment with such approach too.

However as of now, with single cpuid test, I see no point in adding this. After all we already have cpuid test in the pm files right?

Would it be OK to add more rational (in the git commit) explaining why  you propose such thing? 
In the end we must maintain all the tests, so I wonder if having many approaches to the hpc testing isn't somehow counterproductive.

**Comment by b10n1k** [comment]
https://github.com/schlad/hpc-testing/pull/1

**Comment by nmorey** [comment]
On a wider note: if tests needs to be added to this repo that are not specific to a single network type (ib, rxe, siw, etc.), they need to be put in the common helpers so they can/will be run in ALL the test suites.
If it doesn't fit in any of these boxes, it probably shouldn't be in this repo at all.
Let's remember that the sole reason this repo was created is to test RDMA hardware. Not the HPC stack.

**Comment by nmorey** [comment]
> Not the HPC stack.

And yes, I do realize the name was badly picked (by me IIRC) :)

**Pull request closed without merging**
